# Generated by Django 5.0.6 on 2024-06-13 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('reference_name', models.CharField(max_length=255)),
                ('facility', models.CharField(max_length=255)),
                ('telescope', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('spectral_type', models.CharField(max_length=255)),
                ('effective_temperature', models.FloatField()),
                ('radius', models.FloatField()),
                ('mass', models.FloatField()),
                ('metallicity', models.FloatField()),
                ('metallicity_ratio', models.CharField(max_length=255)),
                ('surface_gravity', models.FloatField()),
                ('distance', models.FloatField()),
                ('v_magnitude', models.FloatField()),
                ('k_magnitude', models.FloatField()),
                ('gaia_magnitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemParameterReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('right_ascension', models.CharField(max_length=255)),
                ('ra_degrees', models.FloatField()),
                ('declination', models.CharField(max_length=255)),
                ('dec_degrees', models.FloatField()),
                ('row_update', models.DateField()),
                ('planet_publication_date', models.DateField()),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default_flag', models.BooleanField()),
                ('controversial_flag', models.BooleanField()),
                ('parameter_reference', models.CharField(max_length=255)),
                ('orbital_period', models.FloatField()),
                ('semi_major_axis', models.FloatField()),
                ('radius', models.FloatField()),
                ('mass', models.FloatField()),
                ('mass_sin_i_earth', models.FloatField()),
                ('mass_sin_i_jupiter', models.FloatField()),
                ('mass_provenance', models.CharField(max_length=255)),
                ('eccentricity', models.FloatField()),
                ('insolation_flux', models.FloatField()),
                ('equilibrium_temperature', models.FloatField()),
                ('inclination', models.FloatField()),
                ('ttv_flag', models.BooleanField()),
                ('transit_duration', models.FloatField()),
                ('discovery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planet', to='midterm_app.discovery')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets', to='midterm_app.host')),
            ],
        ),
        migrations.CreateModel(
            name='PlanetarySystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system', to='midterm_app.host')),
                ('parameter_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systems', to='midterm_app.systemparameterreference')),
            ],
        ),
    ]
