# Generated by Django 5.0.4 on 2024-07-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midterm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discovery',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='effective_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='gaia_magnitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='k_magnitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='metallicity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='metallicity_ratio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='surface_gravity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='v_magnitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='controversial_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='planet',
            name='default_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='planet',
            name='eccentricity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='equilibrium_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='inclination',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='insolation_flux',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='mass_provenance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='mass_sin_i_earth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='mass_sin_i_jupiter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='orbital_period',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='parameter_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='semi_major_axis',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='transit_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='ttv_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemparameterreference',
            name='dec_degrees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemparameterreference',
            name='planet_publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemparameterreference',
            name='ra_degrees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemparameterreference',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemparameterreference',
            name='row_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
