# Generated by Django 5.0.4 on 2024-07-06 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midterm_app', '0002_alter_discovery_year_alter_host_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='discovery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets', to='midterm_app.discovery'),
        ),
    ]
